# fly.toml app configuration file generated for hassan1810-ebbt5g on 2026-05-17T15:52:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hassan1810-ebbt5g'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
